export const globalState = {
  connectedAccount: "",
  fundTreasuryModal: "scale-0",
  createOrgModal: "scale-0",
  updateOrgModal: "scale-0",
  createPayrollModal: "scale-0",
  updatePayrollModal: "scale-0",
  workerDetailsModal: "invisible",
  updateWorkerModal: "scale-0",
  createWorkerModal: "scale-0",
  allOrgs: [],
  orgs: [],
  payrolls: [],
  allPyrolls: [],
  payroll: null,
  workers: [],
  stats: {
    id: 0,
    account: "",
    cuts: "0",
    balance: "0",
    name: "",
    description: "",
    payments: 0,
    payrolls: 0,
    workers: 0,
  },
};
